Add http 3xx status codes
splashkit/splashkit-core pull request #119
Opened 2020-08-31 07:55 UTC by hugglesfox

Add 301, 302 and 303 status codes to `http_status_code`

2020-09-03 03:39 UTC, macite requested changes
Perhaps we look at removing `code_to_status`... what do you think? This isn't had public so it could just be a static cast.

Lets fix that as part of this PR.

2020-09-03 04:07 UTC, hugglesfox commented
Sounds like a good idea to me. I'll do that now.

2020-09-04 02:32 UTC, macite requested changes
Just a simple fix - should be able to merge then. Thanks for the contributions.

2020-09-04 02:32 UTC, macite commented on coresdk/src/backend/web_driver.cpp
> +        result->code = static_cast<http_status_code>((int)status);
Remove the (int) cast as well - the static cast should be fine without that.

2020-09-04 03:08 UTC, macite approved these changes
All good!

2020-09-04 03:08 UTC, merged