added particle system frontend
splashkit/splashkit-core pull request #194
Opened 2024-12-05 20:55 UTC by Eswar-S-Sethu

# Description

_I implemented the frontend of the particle system using SplashKit functions. SDL backend is being developed at the moment._

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

_Since the particle system files are separate, I tested it after building the library. All the functionalities I added worked successfully._

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-12-06 03:35 UTC, matt439 requested changes
I like the idea of including particles in SplashKit as they could greatly enhance the visuals or gameplay of a game. In this PR there are some formatting issues to resolve as well as the need for more comprehensive documentation of the methods. The PR documentation should also be fleshed out.

I think it would help greatly to include a simple demonstration of the particle system working. It could be added to `test_graphics.cpp` or a similar file. That way it would be much easier to appreciate how it works.

2024-12-06 03:35 UTC, matt439 commented on coresdk/src/coresdk/particle_system.h
> +#define PI 3.14 // setting the PI value
M_PI is defined in cmath so no need to redefine.

2024-12-06 03:35 UTC, matt439 commented on coresdk/src/coresdk/particle_system.h
> +struct Particle
Structs normally use snake_case naming in SK.

2024-12-06 03:35 UTC, matt439 commented on coresdk/src/coresdk/particle_system.h
> +struct ParticleSystem
Snake case would be best here too.

2024-12-06 03:35 UTC, matt439 commented on coresdk/src/coresdk/particle_system.h
> +
Empty lines.

2024-12-06 03:35 UTC, matt439 commented on coresdk/src/coresdk/particle_system.h
> +
Empty lines.

2024-12-06 03:35 UTC, matt439 commented on coresdk/src/coresdk/particle_system.h
> +// Initialize the particle system
All of the methods below will need more comprehensive documentation. See some of the other header files for reference of the required format.

2024-12-06 03:35 UTC, matt439 commented on structure.txt
Is this auto-generated? Would be best to not include this in the PR if its not required.

2024-12-06 03:35 UTC, matt439 commented on coresdk/src/coresdk/particle_system.h
> +    Particle particles[MAX_PARTICLES]; // Array of particles
Is there always going to be the maximum number of particles? If not, std::vector could save some memory.

2024-12-06 03:38 UTC, matt439 commented
Oh and I just realized this PR is to the main splashkit-core repository, when it should be against the Thoth Tech fork: https://github.com/thoth-tech/splashkit-core

2024-12-08 07:03 UTC, NoahJCross requested changes

2024-12-08 07:03 UTC, NoahJCross commented on coresdk/src/coresdk/particle_system.cpp
The core functionality is solid, but my suggested changes will help it integrate better with SplashKit's FFI requirements and type consistency.

2025-01-07 22:28 UTC, macite commented
It looks like you have inadvertently included a large number of files that seem to be unchanged. You will need to look at this if you want this merged at some point, as we cannot accept this as it is at the moment.

2025-01-10 09:54 UTC, closed without merging